// <auto-generated />
using System;
using Crd.DataAccess.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crd.DataAccess.Migrations.Migrations
{
    [DbContext(typeof(CdrDbContext))]
    partial class CdrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Crd.DataAccess.Migrations.DbModels.CallRecord", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(33)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CallDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CallerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPence")
                        .HasPrecision(11, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyIsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<uint>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Reference");

                    b.ToTable("CallRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
